#!/bin/bash

chistatus=0
BASEDIR=$(dirname "$0")
#echo "$BASEDIR"

abstract()
{
    if [ -z $1 ]
    then
        echo "Avialable abstractions: db, tables";
    else
        case $1 in
            tables) 
            echo "Host: "
            read host
            echo "dbname: "
            read dbname
            echo "username: "
            read user
            echo "password: "
            read pass
            echo "Host: $host , DBName: $dbname , User: $user , Password: $password"
            php-cgi -f "$BASEDIR/index.php" host=$host dbname=$dbname user=$user pass=$pass output=$PWD at=1 | cat
            echo "\nDo you want to open the output folder? [y/n] or [c] if you want to open the project with vscode (you need to install vscode CLI):"
            read response
            if [ $response = "y" ]
            then
                open $PWD
            else
                if [ $response = "c" ]
                then
                    code -g $PWD
                fi
            fi
            ;;
            db) 
            echo "Host: "
            read host
            echo "dbname: "
            read dbname
            echo "username: "
            read user
            echo "password: "
            read pass
            echo "Host: $host , DBName: $dbname , User: $user , Password: $password"
            php-cgi -f "$BASEDIR/index.php" host=$host dbname=$dbname user=$user pass=$pass output=$PWD at=0 | cat
            ;;
        esac
    fi
}

command=$1
case $command in
    abstract) abstract $2;;
    -help) echo "comming soon";;
    -v) echo "v 1.0.0";;
    *) echo "Invalid option";;
esac